version: 0.0
os: linux
files:
  - source: /aws/ec2
    destination: /usr/local/codedeployresources
hooks:
  BeforeInstall:
    - location: aws/ec2/scripts/before-install.sh
      timeout: 300
      runas: root
    - location: aws/ec2/scripts/before-install-nopriv.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: aws/ec2/scripts/after-install.sh
      timeout: 300
      runas: root
    - location: aws/ec2/scripts/after-install-nopriv.sh
      timeout: 300
      runas: ec2-user