version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/codedeployresources
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
    - location: scripts/before-install-nopriv.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: dev/after-install.sh
      timeout: 300
      runas: root
    - location: dev/after-install-nopriv.sh
      timeout: 300
      runas: ec2-user