---
name: Deploy
on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: myGithubActions
    - name: Install NodeJS 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Build SvelteKit
      run: npm run build
    - name: Copy build artifacts to S3
      run: aws s3 cp build s3://${{ secrets.AWS_BUCKET_NAME }}/artifacts/ --recursive
    - name: Copy static assets to S3
      run: aws s3 cp static s3://${{ secrets.AWS_BUCKET_NAME }}/static/ --recursive
